version: "3.3"

services:
    mongo:
        image: "mongo:4.4"
        container_name: mongo_database
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ./mongo_data:/data/db
        ports:
            - 27017:27017
